import { github } from "react-code-blocks";

export const iconManifest = {
  /* { System UI Icons } ------------------------------------------------------------------------------------------------------------- */
  arrow: () => import("./SVGs/UI/arrow.svg"),
  arrow_: () => import("./SVGs/UI/arrow_.svg"),
  narrowed_arrow: () => import("./SVGs/UI/narrowed_arrow.svg"),

  /* { context menu } */
  close: () => import("./SVGs/UI/close.svg"),
  close_: () => import("./SVGs/UI/close_.svg"),
  rename: () => import("./SVGs/UI/rename.svg"),
  rename_: () => import("./SVGs/UI/rename_.svg"),
  open_folder: () => import("./SVGs/UI/open_folder.svg"),
  open_file: () => import("./SVGs/UI/open_file.svg"),
  new_folder: () => import("./SVGs/UI/new_folder.svg"),
  new_file: () => import("./SVGs/UI/new_file.svg"),
  fold: () => import("./SVGs/UI/fold.svg"),
  unfold: () => import("./SVGs/UI/unfold.svg"),
  search: () => import("./SVGs/UI/search.svg"),
  copy: () => import("./SVGs/UI/copy.svg"),
  copy_: () => import("./SVGs/UI/copy_.svg"),
  paste: () => import("./SVGs/UI/paste.svg"),
  save: () => import("./SVGs/UI/save.svg"),
  send: () => import("./SVGs/UI/send.svg"),
  send_: () => import("./SVGs/UI/send_.svg"),
  run: () => import("./SVGs/UI/run.svg"),
  settings: () => import("./SVGs/UI/settings.svg"),
  settings_: () => import("./SVGs/UI/settings_.svg"),
  pen: () => import("./SVGs/UI/pen.svg"),
  hammer: () => import("./SVGs/UI/hammer.svg"),
  delete: () => import("./SVGs/UI/delete.svg"),
  delete_: () => import("./SVGs/UI/delete_.svg"),
  wrench_screwdriver: () => import("./SVGs/UI/wrench_screwdriver.svg"),
  menu: () => import("./SVGs/UI/menu.svg"),
  add: () => import("./SVGs/UI/add.svg"),
  add_: () => import("./SVGs/UI/add_.svg"),
  circle: () => import("./SVGs/UI/circle.svg"),
  gray_delete: () => import("./SVGs/UI/gray_delete.svg"),
  red_circle: () => import("./SVGs/UI/red_circle.svg"),
  side_menu: () => import("./SVGs/UI/side_menu.svg"),
  side_menu_: () => import("./SVGs/UI/side_menu_.svg"),
  model: () => import("./SVGs/UI/model.svg"),
  txt: () => import("./SVGs/UI/txt.svg"),
  txt_: () => import("./SVGs/UI/txt_.svg"),
  update: () => import("./SVGs/UI/update.svg"),
  update_: () => import("./SVGs/UI/update_.svg"),
  stop: () => import("./SVGs/UI/stop.svg"),
  stop_: () => import("./SVGs/UI/stop_.svg"),
  download: () => import("./SVGs/UI/download.svg"),
  download_: () => import("./SVGs/UI/download_.svg"),
  drive: () => import("./SVGs/UI/drive.svg"),
  drive_: () => import("./SVGs/UI/drive_.svg"),
  cloud: () => import("./SVGs/UI/cloud.svg"),
  cloud_: () => import("./SVGs/UI/cloud_.svg"),
  more: () => import("./SVGs/UI/more.svg"),
  more_: () => import("./SVGs/UI/more_.svg"),
  terminal: () => import("./SVGs/UI/terminal.svg"),
  terminal_: () => import("./SVGs/UI/terminal_.svg"),
  web: () => import("./SVGs/UI/web.svg"),
  web_: () => import("./SVGs/UI/web_.svg"),
  github: () => import("./SVGs/UI/github.svg"),
  github_: () => import("./SVGs/UI/github_.svg"),
  upload: () => import("./SVGs/UI/upload.svg"),
  upload_: () => import("./SVGs/UI/upload_.svg"),
  folder: () => import("./SVGs/UI/folder.svg"),
  folder_: () => import("./SVGs/UI/folder_.svg"),
  install: () => import("./SVGs/UI/install.svg"),
  install_: () => import("./SVGs/UI/install_.svg"),
  attachment: () => import("./SVGs/UI/attachment.svg"),
  attachment_: () => import("./SVGs/UI/attachment_.svg"),
  edit: () => import("./SVGs/UI/edit.svg"),
  edit_: () => import("./SVGs/UI/edit_.svg"),
  branch: () => import("./SVGs/UI/branch.svg"),
  branch_: () => import("./SVGs/UI/branch_.svg"),

  local_storage: () => import("./SVGs/UI/local_storage.svg"),
  local_storage_: () => import("./SVGs/UI/local_storage_.svg"),
  models: () => import("./SVGs/UI/models.svg"),
  models_: () => import("./SVGs/UI/models_.svg"),
  chat: () => import("./SVGs/UI/chat.svg"),
  chat_: () => import("./SVGs/UI/chat_.svg"),
  vision: () => import("./SVGs/UI/vision.svg"),
  vision_: () => import("./SVGs/UI/vision_.svg"),

  sun: () => import("./SVGs/UI/sun.svg"),
  sun_: () => import("./SVGs/UI/sun_.svg"),
  moon: () => import("./SVGs/UI/moon.svg"),
  moon_: () => import("./SVGs/UI/moon_.svg"),
  star_1: () => import("./SVGs/UI/star_1.svg"),
  star_1_: () => import("./SVGs/UI/star_1_.svg"),
  star_0: () => import("./SVGs/UI/star_0.svg"),
  star_0_: () => import("./SVGs/UI/star_0_.svg"),

  /* {win32} */
  win32_maximize: () => import("./SVGs/UI/win32/maximize.svg"),
  win32_maximize_: () => import("./SVGs/UI/win32/maximize_.svg"),
  win32_minimize: () => import("./SVGs/UI/win32/minimize.svg"),
  win32_minimize_: () => import("./SVGs/UI/win32/minimize_.svg"),
  win32_restore: () => import("./SVGs/UI/win32/restore.svg"),
  win32_restore_: () => import("./SVGs/UI/win32/restore_.svg"),

  /* { System UI Icons } ------------------------------------------------------------------------------------------------------------- */

  /* { File types Icons } ------------------------------------------------------------------------------------------------------------ */

  /* { Programming Languages } */
  JS: () => import("./SVGs/file_types/js.svg"),
  TS: () => import("./SVGs/file_types/ts.svg"),
  HTML: () => import("./SVGs/file_types/html.svg"),
  CSS: () => import("./SVGs/file_types/css.svg"),
  IPYNB: () => import("./SVGs/file_types/ipynb.svg"),
  JSON: () => import("./SVGs/file_types/json.svg"),
  PY: () => import("./SVGs/file_types/py.svg"),
  JAVA: () => import("./SVGs/file_types/java.svg"),
  C: () => import("./SVGs/file_types/c.svg"),
  CPP: () => import("./SVGs/file_types/cpp.svg"),
  CS: () => import("./SVGs/file_types/cs.svg"),
  PHP: () => import("./SVGs/file_types/php.svg"),
  SQL: () => import("./SVGs/file_types/sql.svg"),
  SWIFT: () => import("./SVGs/file_types/swift.svg"),

  /* { Image } */
  PNG: () => import("./SVGs/file_types/png.svg"),
  SVG: () => import("./SVGs/file_types/svg.svg"),

  /* { Document } */
  TXT: () => import("./SVGs/file_types/txt.svg"),
  PDF: () => import("./SVGs/file_types/pdf.svg"),
  DOCX: () => import("./SVGs/file_types/docx.svg"),
  XLSX: () => import("./SVGs/file_types/xlsx.svg"),
  PPTX: () => import("./SVGs/file_types/pptx.svg"),
  ENV: () => import("./SVGs/file_types/env.svg"),
  MD: () => import("./SVGs/file_types/md.svg"),
  MARKDOWN: () => import("./SVGs/file_types/markdown.svg"),

  /* { Configuration } */
  DS_STORE: () => import("./SVGs/file_types/DS_store.svg"),
  GITIGNORE: () => import("./SVGs/file_types/gitignore.svg"),
  DOCKERIGNORE: () => import("./SVGs/file_types/dockerignore.svg"),

  /* { Other } */
  ZIP: () => import("./SVGs/file_types/zip.svg"),

  /* { File types Icons } ------------------------------------------------------------------------------------------------------------ */
};
